/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine */

#ifndef _Included_jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine
#define _Included_jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine_TEXTURE_SIZE
#define jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine_TEXTURE_SIZE 512L
/*
 * Class:     jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine
 * Method:    drawImageJNI
 * Signature: (FFFFF[[[[I[[[[ZIIIIIIII[FI)V
 */
JNIEXPORT void JNICALL Java_jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine_drawImageJNI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jobjectArray, jobjectArray, jint, jint, jint, jint, jint, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine
 * Method:    drawSingleImageJNI
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_jp_archilogic_docnext_android_coreview_image_CoreImageRenderEngine_drawSingleImageJNI
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
